### ISSUE TITLE
Fix wp_mail_content_type filter

### ISSUE THREAD

**Issue by schoenkaft** [grrr-amsterdam/simply-static#1]
It breaks native user registration/password-reset e-mails.

See also https://github.com/grrr-amsterdam/ocean-cleanup-cms/pull/112 (private)

**Comment by schoenkaft** [comment]
This just landed. I've just disabled the whole filter.

**Comment by wp-seth** [comment]
great!
this also fixes
  https://wordpress.org/support/topic/bug-ss-changes-e-mail-content-type-from-plain-to-html/
where unfortunately i can't add the information, because that remote issue is closed for no reason.
