### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by pedrolaranjeiro** [grrr-amsterdam/simply-static#5]
Hi
Thank you for you work progressing simple static to later versions of php. 
Can you add a section of how to compile this plugin? I followed the WP2Static instructions [here](https://wp2static.com/compiling-from-source/) but I got an exception.

The commands I used where

- composer install
- composer build simple-static-2.1.0

The exception I encountered was
```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "build" is not defined. 
```

Can you help me please?

**Comment by harmenjanssen** [comment]
I there! 
To make this package a dependency of your project, use `composer require`:

```
composer require grrr-amsterdam/simply-static
```
